### ISSUE TITLE
example code mentions img_to_vec -> but think it's supposed to be img_to_vec_keras 

### ISSUE THREAD

**Issue by johndpope** [jaredwinick/img2vec-keras#4]

**Comment by johndpope** [comment]
also - (tf10) ➜  examples git:(master) ✗ python similarity.py
Using Theano backend.
/Users/jpope/miniconda3/envs/tf10/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "similarity.py", line 10, in <module>
    cat1_vec = img2vec.get_vec('images/cat1.jpg')
  File "/Users/jpope/miniconda3/envs/tf10/lib/python3.7/site-packages/img2vec_keras-0.1-py3.7.egg/img2vec_keras/img_to_vec.py", line 30, in get_vec
    return intermediate_output[0][0][0]
IndexError: invalid index to scalar variable.
(tf10) ➜  examples git:(master) ✗ l

do I need to install resnet?
https://github.com/broadinstitute/keras-resnet

**Comment by jaredwinick** [comment]
Thanks, I fixed the import. I am able to recreate the IndexError you are reporting as well at https://colab.research.google.com/drive/1-0YTIH4Hk7Bw0BF0OUmH69QF6Iywd5oR. I will try to find a chance to resolve this. thanks.

**Comment by jaredwinick** [comment]
@johndpope I resolved the IndexError. I had the wrong shape on the `intermediate_output` variable
